admin = User.create!(first_name: "Rick", last_name: "Do", username: "rickyd", email: "datvietburrido@gmail.com", city: "Houston", state: "Texas", number_of_posts: 0, clearance: "admin", password: "password", password_confirmation: "password")
mod = User.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, username: "mod_1", email: "g3tdo@yahoo.com", city: "Houston", state: "Texas", number_of_posts: 0, clearance: "moderator", password: "password", password_confirmation: "password")
user_1 = User.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, username: "user_1", email: "ricky.dop@gmail.com", city: "Houston", state: "Texas", number_of_posts: 0, clearance: "registered", password: "password", password_confirmation: "password")
user_2 = User.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, username: "user_2", email: "tuantonyd@gmail.com", city: "Houston", state: "Texas", number_of_posts: 0, clearance: "registered", password: "password", password_confirmation: "password")

Signature.create!(user_id: admin.id, content: "Boss Signature")
Signature.create!(user_id: mod.id, content: "Moderator's Sig")
Signature.create!(user_id: user_1.id, content: "User 1 Signature")
Signature.create!(user_id: user_2.id, content: "User 2 Sig")

intro = Category.create!(name: "Introduction", description: "Just joined the forum? Introduce yourself and your ride if you want.")
gd = Category.create!(name: "General Discussion", description: "Talk about cars in general")
sales = Category.create!(name: "Classifieds", description: "Want to sell or buy something? Post here")
repair = Category.create!(name: "Maintenance", description: "Keep your vehicles running like new")
Category.create!(name: "Appearance Mods", description: "To each their own")
Category.create!(name: "Forced Induction", description: "Must...go...faster...zoom")
Category.create!(name: "Tires", description: "Here lies the threads about tires."
Category.create!(name: "Wheels", description: "Yes they are called wheels, not rims.")


t1 = ThreadForPost.create!(subject: Faker::Hacker.ingverb + " " +  Faker::Hacker.adjective + " " + Faker::Hacker.noun, text: Faker::Hacker.say_something_smart, user_id: mod.id, category_id: intro.id)
t2 = ThreadForPost.create!(subject: Faker::Hacker.ingverb + " " +  Faker::Hacker.adjective + " " + Faker::Hacker.noun, text: Faker::Hacker.say_something_smart, user_id: user_1.id, category_id: sales.id )
t3 = ThreadForPost.create!(subject: Faker::Hacker.ingverb + " " +  Faker::Hacker.adjective + " " + Faker::Hacker.noun, text: Faker::Hacker.say_something_smart, user_id: user_2.id, category_id: gd.id)
t4 = ThreadForPost.create!(subject: Faker::Hacker.ingverb + " " + Faker::Hacker.adjective + " " + Faker::Hacker.noun, text: Faker::Hacker.say_something_smart, user_id: user_1.id , category_id: gd.id)
t5 = ThreadForPost.create!(subject: Faker::Hacker.ingverb + " " + Faker::Hacker.adjective + " " + Faker::Hacker.noun, text: Faker::Hacker.say_something_smart, user_id: admin.id , category_id: repair.id, stickied: true )

Post.create!(text: Faker::Lorem.paragraph, user_id: admin.id , thread_for_post_id: t1.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: mod.id, thread_for_post_id: t2.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: mod.id, thread_for_post_id: t3.id)
Post.create!(text: Faker::Lorem.paragraph, user_id: user_1.id, thread_for_post_id: t4.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: user_1.id, thread_for_post_id: t3.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: user_1.id, thread_for_post_id: t2.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: user_1.id, thread_for_post_id: t5.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: user_1.id, thread_for_post_id: t5.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: user_2.id, thread_for_post_id: t1.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: user_2.id, thread_for_post_id: t2.id )
Post.create!(text: Faker::Lorem.paragraph, user_id: user_2.id, thread_for_post_id: t4.id )
